"""CompetencyProposal ORM model.

Stores LLM-extracted competency candidates awaiting Consultant review.
Each proposal references a PublicSource and includes evidence and confidence level.

Requirements: 2.1, 2.3
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.profile_enrichment_audit import ProfileEnrichmentAudit
    from app.models.public_source import PublicSource


class CompetencyProposal(Base):
    """A competency proposal generated by the Profile Enrichment Worker."""

    __tablename__ = "competency_proposals"
    __table_args__ = (
        CheckConstraint(
            "confidence IN ('strong', 'inferred')",
            name="competency_proposals_valid_confidence",
        ),
        CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')",
            name="competency_proposals_valid_status",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    consultant_id: Mapped[str] = mapped_column(String(50), nullable=False)
    source_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("public_sources.id"), nullable=False
    )
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    name: Mapped[str] = mapped_column(String(500), nullable=False)
    evidence_summary: Mapped[str] = mapped_column(Text, nullable=False)
    raw_evidence: Mapped[str | None] = mapped_column(Text, nullable=True)
    confidence: Mapped[str] = mapped_column(String(20), nullable=False)
    source_url: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(
        String(20), server_default="'pending'", nullable=False
    )
    merged_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("NOW()"), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("NOW()"), nullable=False
    )

    # Relationships
    source: Mapped["PublicSource"] = relationship(
        "PublicSource", back_populates="competency_proposals"
    )
    audit_entries: Mapped[list["ProfileEnrichmentAudit"]] = relationship(
        "ProfileEnrichmentAudit", back_populates="proposal"
    )
