"""Data models and error hierarchy for the Interview Prep Technique (P8).

Requirements 2.1: Pack structural definitions (questions, STAR talking points,
company briefing, questions to ask).
Requirements 2.2: STAR_Talking_Point structure with grounding references and
gap-handling support.

These models are used by the Interview_Prep_Service during pack generation,
by the Grounding_Verifier for claim verification, and by the API layer
for serialization and delivery.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


# ─── ENUMS ────────────────────────────────────────────────────────────────────


class PackStatus(str, Enum):
    """Lifecycle status of an Interview_Prep_Pack.

    Tracks the pack through generation, grounding verification, and delivery.

    Values:
        GENERATING: LLM generation is in progress.
        GROUNDING: Pack generated; Grounding_Verifier is verifying claims.
        READY: All STAR claims grounded successfully; pack is deliverable.
        READY_WITH_FLAGS: Pack delivered but some grounding flags remain
            after the single regeneration attempt.
        FAILED: Generation failed after all retries; surfaced in
            Dashboard "Requires Action" without blocking pipeline.
    """

    GENERATING = "generating"
    GROUNDING = "grounding"
    READY = "ready"
    READY_WITH_FLAGS = "ready_with_flags"
    FAILED = "failed"


class GapHandlingStrategy(str, Enum):
    """Strategy for handling a competency gap in a STAR talking point.

    When the opportunity demands a competency the Consultant's profile does
    not directly evidence, one of these strategies frames the gap honestly
    rather than fabricating a narrative.

    Values:
        ADJACENT_EXPERIENCE: Frame using closely related work in the same domain.
        TRANSFERABLE_SKILL: Highlight a transferable skill from a different domain
            that applies to the required competency.
        LEARNING_TRAJECTORY: Present a credible learning path or current
            development effort toward the competency.
    """

    ADJACENT_EXPERIENCE = "adjacent_experience"
    TRANSFERABLE_SKILL = "transferable_skill"
    LEARNING_TRAJECTORY = "learning_trajectory"


# ─── DATACLASSES ──────────────────────────────────────────────────────────────


@dataclass
class STAR_Talking_Point:
    """A Situation-Task-Action-Result narrative for an anticipated competency question.

    Each talking point maps a likely interview question to a structured narrative
    drawn exclusively from the Consultant's verified profile assets. When the
    opportunity demands a competency not evidenced in the profile, the point is
    marked as gap-handled with an honest framing note.

    Attributes:
        competency: The competency or skill area being addressed.
        question: The anticipated interview question this point answers.
        situation: The context/setting from the Consultant's experience.
        task: What was required in that situation.
        action: What the Consultant did (from profile evidence).
        result: The measurable outcome achieved.
        source_asset_refs: Asset IDs from which this narrative is drawn.
            Must contain at least one entry for grounding traceability.
        is_gap_handled: True if the opportunity demands a competency the
            profile does not directly evidence.
        gap_note: Framing note explaining how adjacent experience applies.
            Must be non-empty when is_gap_handled is True.
    """

    competency: str
    question: str
    situation: str
    task: str
    action: str
    result: str
    source_asset_refs: list[str]
    is_gap_handled: bool = False
    gap_note: str | None = None


@dataclass
class Interview_Prep_Pack:
    """The complete interview preparation pack delivered to the Consultant.

    Generated by Interview_Prep_Service on Interview state entry. Contains
    likely questions, STAR talking points, a company briefing, and suggested
    questions for the Consultant to ask. All Beneficiary-side claims pass
    through the Grounding_Verifier before delivery.

    Structural constraints (validated post-generation):
        - likely_questions: between 8 and 15 entries
        - star_talking_points: exactly 5 entries
        - company_briefing: at most 400 words
        - questions_to_ask: between 3 and 6 entries

    Attributes:
        id: UUID primary key.
        pipeline_record_id: The pipeline record that triggered generation.
        beneficiary_id: The Consultant (Beneficiary) this pack is for.
        opportunity_type_id: The schema opportunity type (e.g. job_site).
        likely_questions: 8-15 anticipated interview questions derived from
            the opportunity's requirements and responsibilities.
        star_talking_points: Exactly 5 STAR narratives for the most probable
            competency-based questions.
        company_briefing: Max 400-word briefing synthesized from the
            Enrichment_Record, focused on interview-useful context.
        questions_to_ask: 3-6 informed questions for the Consultant to ask,
            grounded in the Enrichment_Record.
        status: Current lifecycle status of the pack.
        omission_notes: Notes about missing context inputs (e.g. submitted
            CV unavailable, proceeding with profile only).
        grounding_flags: Remaining grounding issues after single regeneration
            attempt. Empty when status is READY.
        generation_duration_ms: Wall-clock time for the generation pipeline.
        created_at: When this pack version was created.
        updated_at: Last modification timestamp.
    """

    id: str
    pipeline_record_id: str
    beneficiary_id: str
    opportunity_type_id: str
    likely_questions: list[str]
    star_talking_points: list[STAR_Talking_Point]
    company_briefing: str
    questions_to_ask: list[str]
    status: PackStatus
    omission_notes: list[str] = field(default_factory=list)
    grounding_flags: list[str] = field(default_factory=list)
    generation_duration_ms: int = 0
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class GenerationContext:
    """Assembled inputs for Interview_Prep_Pack generation.

    Collected by Interview_Prep_Service.assemble_context() from the pipeline
    record's opportunity, submitted materials, Enrichment_Record, and
    Consultant profile assets.

    Postconditions enforced by context assembly:
        - opportunity_description is always non-empty
        - enrichment_record is always present
        - profile_assets has at least one entry

    Attributes:
        opportunity_description: The opportunity's description text used to
            derive likely questions and competency requirements.
        tailored_cv: The submitted CV for this pipeline record, or None if
            the Consultant has not yet submitted one.
        tailored_cover_letter: The submitted cover letter, or None if not
            yet submitted.
        enrichment_record: The prospect's Enrichment_Record containing company
            data, intent signals, and technology stack.
        intent_signals: Intent signals from the Enrichment_Record, used for
            company briefing and questions-to-ask generation.
        profile_assets: Mapping of asset_id to content for the Consultant's
            profile assets (resume, consultant_profiles, etc.).
        star_examples: Existing STAR example material from the Consultant's
            profile, if available.
        opportunity_type_id: Schema opportunity type identifier.
        beneficiary_id: The Consultant (Beneficiary) identifier.
    """

    opportunity_description: str
    tailored_cv: str | None
    tailored_cover_letter: str | None
    enrichment_record: Any  # EnrichmentRecord
    intent_signals: list[Any]  # list[IntentSignal]
    profile_assets: dict[str, str]  # asset_id -> content
    star_examples: list[dict] | None
    opportunity_type_id: str
    beneficiary_id: str


# ─── ERROR HIERARCHY ──────────────────────────────────────────────────────────


class InterviewPrepError(Exception):
    """Base error class for all interview prep generation failures.

    All interview prep errors carry a pipeline_record_id (the record whose
    pack generation failed) and a retryable flag indicating whether the
    operation can be retried by the worker.

    Follows the same pattern as GroundingError for consistent error handling
    across the generation pipeline.

    Attributes:
        message: Human-readable error description.
        pipeline_record_id: The pipeline record being processed when the
            error occurred.
        retryable: Whether the worker should retry this operation.
        details: Optional dictionary of additional context for logging.
    """

    def __init__(
        self,
        message: str,
        *,
        pipeline_record_id: str,
        retryable: bool = True,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.pipeline_record_id = pipeline_record_id
        self.retryable = retryable
        self.details = details or {}

    def __str__(self) -> str:
        return (
            f"{self.message} [pipeline_record_id={self.pipeline_record_id}, "
            f"retryable={self.retryable}]"
        )

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"message={self.message!r}, "
            f"pipeline_record_id={self.pipeline_record_id!r}, "
            f"retryable={self.retryable!r})"
        )


class GenerationTimeoutError(InterviewPrepError):
    """Raised when LLM generation exceeds the 90-second timeout.

    This error is retryable — the Interview_Prep_Service will retry
    generation up to MAX_RETRIES times before marking the pack as failed.

    Attributes:
        timeout_seconds: The timeout threshold that was exceeded.
    """

    def __init__(
        self,
        message: str = "Interview prep generation timed out",
        *,
        pipeline_record_id: str,
        retryable: bool = True,
        timeout_seconds: float = 90.0,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(
            message,
            pipeline_record_id=pipeline_record_id,
            retryable=retryable,
            details=details,
        )
        self.timeout_seconds = timeout_seconds


class DeadlineExceededError(InterviewPrepError):
    """Raised when the total generation pipeline exceeds the 120-second deadline.

    This error is NOT retryable — the overall deadline has been breached and
    the pack should be marked as failed immediately. The failure is surfaced
    in the Dashboard "Requires Action" section without blocking any pipeline
    state transition.

    Attributes:
        deadline_seconds: The deadline threshold that was exceeded.
    """

    def __init__(
        self,
        message: str = "Interview prep generation exceeded 120-second deadline",
        *,
        pipeline_record_id: str,
        retryable: bool = False,
        deadline_seconds: float = 120.0,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(
            message,
            pipeline_record_id=pipeline_record_id,
            retryable=retryable,
            details=details,
        )
        self.deadline_seconds = deadline_seconds


class PackValidationError(InterviewPrepError):
    """Raised when a generated pack does not meet structural constraints.

    The pack failed validation checks (question counts, STAR count, briefing
    word limit, etc.). This is retryable — the service will attempt generation
    again with a stricter prompt.

    Attributes:
        validation_errors: List of specific constraint violations found.
    """

    def __init__(
        self,
        message: str = "Generated pack does not meet structural constraints",
        *,
        pipeline_record_id: str,
        validation_errors: list[str],
        retryable: bool = True,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(
            message,
            pipeline_record_id=pipeline_record_id,
            retryable=retryable,
            details=details,
        )
        self.validation_errors = validation_errors


class ContextAssemblyError(InterviewPrepError):
    """Raised when minimum required context for generation cannot be assembled.

    This occurs when critical inputs are missing (e.g. no opportunity
    description, no Enrichment_Record, or no profile assets at all).
    This error is NOT retryable because the required data simply does
    not exist — retrying will not produce a different result.

    Attributes:
        missing_inputs: List of required inputs that could not be loaded.
    """

    def __init__(
        self,
        message: str = "Failed to assemble minimum required context for generation",
        *,
        pipeline_record_id: str,
        missing_inputs: list[str] | None = None,
        retryable: bool = False,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(
            message,
            pipeline_record_id=pipeline_record_id,
            retryable=retryable,
            details=details,
        )
        self.missing_inputs = missing_inputs or []
